version: '3.9'
name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    ports:
      - "443:443"
    networks:
      - frontend
      - backend
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/data/wordpress/:ro
    configs:
      - source: nginx_config
        target: /etc/nginx/http.d/default.conf
    environment:
      - DOMAIN_NAME
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    networks:
      - backend
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress_files:/data/wordpress/
    configs:
      - source: wp_pool_conf
        target: /etc/php8/php-fpm.d/wp_pool.conf
    environment:
      - MARIADB_HOST
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - DOMAIN_NAME
      - WP_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_MAIL
      - WP_USER_MAIL
      - WP_USER_PASS
      - WP_USER_USER
      - COMPOSE_PROFILES
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - backend
    expose:
      - "3306"
    volumes:
      - wordpress_db:/data/wordpress_db/
    configs:
      - source: mariadb_conf
        target: /etc/my.cnf.d/mariadb.conf
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    restart: on-failure

  redis:
    profiles:
      - bonus
    container_name: redis
    build:
      context: requirements/bonus/redis
    networks:
      - backend
    expose:
      - "6379"
    configs:
      - source: redis_conf
        target: /etc/redis/redis.conf
    restart: on-failure

  ftp:
    profiles:
      - bonus
    container_name: ftp
    build:
      context: requirements/bonus/ftp
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
    ports:
      - "20"
      - "21"
      - "990"
      - "21000-21010"
    networks:
      - frontend
    volumes:
      - wordpress_files:/data/wordpress/
    configs:
      - source: ftp_conf
        target: /etc/vsftpd/vsftpd.conf
    restart: on-failure

volumes:
  wordpress_files:
    driver: local
    name: wordpress_files
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  wordpress_db:
    driver: local
    name: wordpress_db
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress_db

configs:
  nginx_config:
    name: nginx_config
    file: ./requirements/nginx/conf/nginx.conf
  wp_pool_conf:
    name: wp_pool_conf
    file: ./requirements/wordpress/conf/wp_pool.conf
  mariadb_conf:
    name: mariadb_conf
    file: ./requirements/mariadb/conf/mariadb.conf
  redis_conf:
    name: redis_conf
    file: ./requirements/bonus/redis/conf/redis.conf
  ftp_conf:
    name: ftp_conf
    file: ./requirements/bonus/ftp/conf/vsftpd.conf

networks:
  frontend:
  backend:
