version: '3.9'
name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    ports:
      - "443:443"
    networks:
      - backend
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/data/wordpress
    configs:
      - source: nginx_config
        target: /etc/nginx/http.d/default.conf
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    networks:
      - backend
    depends_on:
      - mariadb
    volumes:
      - wordpress_files:/data/wordpress
    configs:
      - source: wp_pool_conf
        target: /etc/php8/php-fpm.d/wp_pool.conf
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - WP_USER_PASS=${WP_USER_PASS}
      - WP_USER_USER=${WP_USER_USER}
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - backend
    expose:
      - "3306"
    volumes:
      - wordpress_db:/data/wordpress_db/
    configs:
      - source: mariadb_conf
        target: /etc/my.cnf.d/mariadb.conf
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  wordpress_files:
    driver: local
    name: wordpress_files
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  wordpress_db:
    driver: local
    name: wordpress_db
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress_db

configs:
  nginx_config:
    name: nginx_config
    file: ./requirements/nginx/conf/nginx.conf
  wp_pool_conf:
    name: wp_pool_conf
    file: ./requirements/wordpress/conf/wp_pool.conf
  mariadb_conf:
    name: mariadb_conf
    file: ./requirements/mariadb/conf/mariadb.conf

networks:
  backend:
